#pragma once
#include "D:\los_projectados\wtfProc\lib\globalization.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include header(flog)
#include header(cmd)
#include header(text)

/// @brief Macros to check for no writing run of writeWtf
#define tagCheck(...) if (outFile != NULL) { \
    __VA_ARGS__                              \
}

/// @brief Counts ip of current unstruction in cpu->code
extern size_t ip;

/// @brief Is a flag for if errors have occured
extern bool errors;

/// @brief Enumerator of command codes (autogenerated)
enum CMD {

    #undef DEF_CMD
    #define DEF_CMD(name, num, arg, code) CMD_##name = num,

    #include header (cmd)
};

/// @brief Masks for different fields of command byte
enum masks {

    MASK_RAM = 1<<7, ///< Ram bit
    MASK_REG = 1<<6, ///< Register bit
    MASK_IMM = 1<<5, ///< Immidiate constant bit
    MASK_CMD = (1<<5) - 1, ///<Bits for command number
};

/// @brief Macros for writeBinInternal
#define writeBin(var, outFile) writeBinInternal (&var, outFile, sizeof (var))

/// @brief Internal function for writeBin macros. Is a memcpy to file basically
/// @param val Value to write
/// @param outFile File to write to
/// @param sizeOfVar Size of variable
void writeBinInternal (void* val, FILE* outFile, size_t sizeOfVar);

/// @brief Handles argument of a command
/// @param code Text of program in asm
/// @param line Current line
/// @param outFile File to write to
/// @param cmdNum Number of command it's counting arg for
/// @param tags Array of tags for jumps
void handleArg (Text* code, int line, FILE* outFile, char cmdNum, int tags[512]);

/// @brief Handles command line arguments
/// @param argc Amount of arguments
/// @param argv Array of arguments
/// @param aFlag Wrote by function. Indicates if no check for up to date (unused currently)
/// @param outFileName Wrote by function. Name of file to write to
/// @return Name of file to read from
char* handleComLine (int argc, char* argv[], bool* aFlag, char** outFileName);

/// @brief Writes into a .wtf binary file
/// @param codeFile Struct with source code
/// @param outFile File to write to
/// @param tags Array of tags for jumps
void writeWtf (Text* codeFile, FILE* outFile, int tags[512]);