.TH "asm/asm.cpp" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/asm.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'asm_head\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "size_t \fBip\fP = 0"
.br
.ti -1c
.RI "bool \fBerrors\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 7 of file asm\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "bool errors = 0"

.PP
Definition at line 5 of file asm\&.cpp\&.
.SS "size_t ip = 0"

.PP
Definition at line 3 of file asm\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Soft cpu from the source code\&.
