.TH "lib/cmd.h" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cmd.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBelem_t_F\fP   '%Lf'"
.br
.RI "Printf format string for elem_t\&. "
.ti -1c
.RI "#define \fBPUSH\fP(val)   \fBStackPush\fP (&cpu\->stk, val)"
.br
.ti -1c
.RI "#define \fBPOP\fP   \fBStackPop\fP (&cpu\->stk)"
.br
.ti -1c
.RI "#define \fBsigna\fP   'CP02'"
.br
.RI "signature of a fine file "
.ti -1c
.RI "#define \fBDEF_CMD\fP(name,  num,  arg,  code)   ;"
.br
.ti -1c
.RI "#define \fBGENERAL_CMD\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef double \fBelem_t\fP"
.br
.RI "Base element of cpu\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEF_CMD(name, num, arg, code)   ;"

.PP
Definition at line 23 of file cmd\&.h\&.
.SS "#define elem_t_F   '%Lf'"

.PP
Printf format string for elem_t\&. 
.PP
Definition at line 16 of file cmd\&.h\&.
.SS "#define GENERAL_CMD"

.PP
Definition at line 26 of file cmd\&.h\&.
.SS "#define POP   \fBStackPop\fP (&cpu\->stk)"

.PP
Definition at line 19 of file cmd\&.h\&.
.SS "#define PUSH(val)   \fBStackPush\fP (&cpu\->stk, val)"

.PP
Definition at line 18 of file cmd\&.h\&.
.SS "#define signa   'CP02'"

.PP
signature of a fine file 
.PP
Definition at line 21 of file cmd\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef double \fBelem_t\fP"

.PP
Base element of cpu\&. 
.PP
Definition at line 15 of file cmd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Soft cpu from the source code\&.
