.TH "asm Directory Reference" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBasm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBasm_funcs\&.cpp\fP"
.br
.ti -1c
.RI "file \fBasm_head\&.h\fP"
.br
.in -1c
