.TH "processor Directory Reference" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
processor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBproc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBproc_funcs\&.cpp\fP"
.br
.ti -1c
.RI "file \fBproc_head\&.h\fP"
.br
.in -1c
