.TH "lib/flog.cpp" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/flog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'flog\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBflogIntern\fP (const void *val, const char *varType, const char *varName, size_t varSize, const char *fileName, const char *funcName, size_t line)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "FILE * \fBlogOutf\fP = NULL"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void flogIntern (const void * val, const char * varType, const char * varName, size_t varSize, const char * fileName, const char * funcName, size_t line)"

.PP
Definition at line 30 of file flog\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "FILE* logOutf = NULL"

.PP
Definition at line 10 of file flog\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Soft cpu from the source code\&.
