.TH "lib/globalization.h" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/globalization.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBpasta\fP(str)   #str"
.br
.ti -1c
.RI "#define \fBpasta\fP(str)   #str"
.br
.ti -1c
.RI "#define \fBheader\fP(fileName)   \fBpasta\fP(D:\\los_projectados\\wtfProc\\lib\\fileName\&.h)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define header(fileName)   \fBpasta\fP(D:\\los_projectados\\wtfProc\\lib\\fileName\&.h)"

.PP
Definition at line 4 of file globalization\&.h\&.
.SS "#define pasta(str)   #str"

.PP
Definition at line 3 of file globalization\&.h\&.
.SS "#define pasta(str)   #str"

.PP
Definition at line 3 of file globalization\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Soft cpu from the source code\&.
