.TH "Line" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line \- Struct to store Lines of \fBText\fP in format [begin, end)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <text\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBbegin\fP = NULL"
.br
.RI "Ptr to the beginning\&. "
.ti -1c
.RI "char * \fBend\fP = NULL"
.br
.RI "Ptr to the end\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct to store Lines of \fBText\fP in format [begin, end) 
.PP
Definition at line 10 of file text\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char* Line::begin = NULL"

.PP
Ptr to the beginning\&. 
.PP
Definition at line 12 of file text\&.h\&.
.SS "char* Line::end = NULL"

.PP
Ptr to the end\&. 
.PP
Definition at line 13 of file text\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Soft cpu from the source code\&.
