.TH "Proc" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Proc \- Struct to store data of a running soft cpu\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <proc_head\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBcode\fP = NULL"
.br
.RI "String of binary code\&. "
.ti -1c
.RI "size_t \fBcodeSize\fP = 0"
.br
.RI "Size of code\&. "
.ti -1c
.RI "\fBelem_t\fP \fBregs\fP [5] = {0}"
.br
.RI "Array of registers\&. "
.ti -1c
.RI "int \fBip\fP = 0"
.br
.RI "Instruction pointer\&. "
.ti -1c
.RI "\fBStack\fP \fBstk\fP = {}"
.br
.RI "\fBStack\fP of elem_t for work of process\&. "
.ti -1c
.RI "\fBStack\fP \fBfuncIp\fP = {}"
.br
.RI "\fBStack\fP of ip for function calls\&. "
.ti -1c
.RI "\fBelem_t\fP * \fBram\fP = NULL"
.br
.RI "Array that represents RAM\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct to store data of a running soft cpu\&. 
.PP
Definition at line 48 of file proc_head\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char* Proc::code = NULL"

.PP
String of binary code\&. 
.PP
Definition at line 50 of file proc_head\&.h\&.
.SS "size_t Proc::codeSize = 0"

.PP
Size of code\&. 
.PP
Definition at line 51 of file proc_head\&.h\&.
.SS "\fBStack\fP Proc::funcIp = {}"

.PP
\fBStack\fP of ip for function calls\&. 
.PP
Definition at line 55 of file proc_head\&.h\&.
.SS "int Proc::ip = 0"

.PP
Instruction pointer\&. 
.PP
Definition at line 53 of file proc_head\&.h\&.
.SS "\fBelem_t\fP* Proc::ram = NULL"

.PP
Array that represents RAM\&. 
.PP
Definition at line 56 of file proc_head\&.h\&.
.SS "\fBelem_t\fP Proc::regs[5] = {0}"

.PP
Array of registers\&. 
.PP
Definition at line 52 of file proc_head\&.h\&.
.SS "\fBStack\fP Proc::stk = {}"

.PP
\fBStack\fP of elem_t for work of process\&. 
.PP
Definition at line 54 of file proc_head\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Soft cpu from the source code\&.
