.TH "Stack" 3 "Sat Oct 15 2022" "Version 2" "Soft cpu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stack \- Stores a stack with several support variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stack\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBcanL\fP = 0xDEADBEEF"
.br
.RI "left cannary of struct "
.ti -1c
.RI "unsigned int \fBhash\fP = 0"
.br
.RI "hash value "
.ti -1c
.RI "size_t \fBsize\fP = 0"
.br
.RI "size of stack "
.ti -1c
.RI "size_t \fBcapacity\fP = 0"
.br
.RI "capacity of stack "
.ti -1c
.RI "size_t \fBerrCode\fP = \fBok\fP"
.br
.RI "error code "
.ti -1c
.RI "\fBELEM_TYPE\fP * \fBstack\fP = NULL"
.br
.RI "ptr to stack "
.ti -1c
.RI "unsigned int * \fBstackCanL\fP = NULL"
.br
.RI "left cannary of stack "
.ti -1c
.RI "unsigned int * \fBstackCanR\fP = NULL"
.br
.RI "right cannary of stack "
.ti -1c
.RI "unsigned int \fBcanR\fP = 0xD34DB33F"
.br
.RI "right cannary of struct "
.in -1c
.SH "Detailed Description"
.PP 
Stores a stack with several support variables\&. 
.PP
Definition at line 55 of file stack\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int Stack::canL = 0xDEADBEEF"

.PP
left cannary of struct 
.PP
Definition at line 57 of file stack\&.h\&.
.SS "unsigned int Stack::canR = 0xD34DB33F"

.PP
right cannary of struct 
.PP
Definition at line 65 of file stack\&.h\&.
.SS "size_t Stack::capacity = 0"

.PP
capacity of stack 
.PP
Definition at line 60 of file stack\&.h\&.
.SS "size_t Stack::errCode = \fBok\fP"

.PP
error code 
.PP
Definition at line 61 of file stack\&.h\&.
.SS "unsigned int Stack::hash = 0"

.PP
hash value 
.PP
Definition at line 58 of file stack\&.h\&.
.SS "size_t Stack::size = 0"

.PP
size of stack 
.PP
Definition at line 59 of file stack\&.h\&.
.SS "\fBELEM_TYPE\fP* Stack::stack = NULL"

.PP
ptr to stack 
.PP
Definition at line 62 of file stack\&.h\&.
.SS "unsigned int* Stack::stackCanL = NULL"

.PP
left cannary of stack 
.PP
Definition at line 63 of file stack\&.h\&.
.SS "unsigned int* Stack::stackCanR = NULL"

.PP
right cannary of stack 
.PP
Definition at line 64 of file stack\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Soft cpu from the source code\&.
